backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'information'
    label: 'Інформація'
    extension: 'html'
    format: 'yaml-frontmatter'
    description: 'інформаційні колонки про школу'
    folder: '_information'
    fields:
      - { name: title, label: 'Розділ', widget: 'string'}
      - { name: title_left, label: 'Заголовок 1 рядок', widget: 'string' }
      - { name: title_right, label: 'Заголовок 2 рядок', widget: 'string' }
      - { name: icon, label: 'Іконка', widget: 'string' }
      - { name: body, label: 'Текст', widget: 'markdown'}
  - name: 'courses'
    label: 'Наші Курси'
    extension: 'html'
    format: 'yaml-frontmatter'
    description: 'окремі сторінки про кожен курс'
    folder: '_courses'
    create: true
    fields:
      - { name: title, label: 'Назва курсу', widget: 'string' }
