backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'information'
    label: 'Інформація'
    extension: 'html'
    format: 'yaml-frontmatter'
    description: 'інформаційні колонки про школу'
    folder: '_information'
    fields:
      - { name: title, label: 'Розділ', widget: 'string'}
      - { name: title_left, label: 'Заголовок 1 рядок', widget: 'string' }
      - { name: title_right, label: 'Заголовок 2 рядок', widget: 'string' }
      - { name: icon, label: 'Іконка', widget: 'string' }
      - { name: body, label: 'Текст', widget: 'markdown'}
  - name: 'courses'
    label: 'Наші Курси'
    extension: 'html'
    format: 'yaml-frontmatter'
    description: 'окремі сторінки про кожен курс'
    folder: '_courses'
    create: true
    fields:
      - { name: layout, label: 'Layout', widget: 'hidden' }
      - { name: title, label: 'Назва курсу', widget: 'string' }
      - { name: price, label: 'Вартість, грн', widget: 'number', value_type: 'int' }
      - name: icon
        label: 'Іконка'
        widget: 'select'
        options:
          - { label: 'Коло', value: 0 }
          - { label: 'Стілки', value: 1 }
          - { label: 'Кілька кіл', value: 2 }
          - { label: 'Півкола', value: 3 }
          - { label: 'Квадрат&Коло', value: 4 }
      - { name: start_at, label: 'Початок з', widget: 'string' }
      - { name: start_age, label: 'Вік учнів від', widget: 'number', value_type: 'int', min: 9, max: 17 }
      - { name: finish_age, label: 'Вік учнів до', widget: 'number', value_type: 'int', min: 9, max: 17 }
      - { name: lessons, label: 'Кількість уроків', widget: 'number', value_type: 'int', min: 1 }
      - name: lesson_time
        label: ''
        widget: 'select'
        options:
          - { label: '45 хвилин', value: '45 хвилин' }
          - { label: 'одна година', value: 'годині' }
          - { label: 'дві години', value: 'дві години' }
      - name: lessons_in_week
        label: 'Кількість занять на тиждень'
        widget: 'select'
        options:
          - { label: 'одне', value: 1 }
          - { label: 'два', value: 2 }
          - { label: 'три', value: 3 }
          - { label: 'чотири', value: 4 }
      - { name: skills, label: 'Опис навичок і вмінь', widget: 'text' }
      - name: program
        label: 'Програма курсу'
        widget: 'list'
        summary: '{{ fields.item }}'
        field: { name: item, label: 'Пункт', widget: 'string'}
